name: Integration Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v3
        with:
          repository: GIBBY-GDGoC-in-GIST/GIBBY_frontend
          path: GIBBY_frontend
          token: ${{ secrets.INTEGRATION_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'GIBBY_frontend/package-lock.json'

      - name: Install Dependencies
        run: |
          cd GIBBY_frontend
          npm ci
          npm list react-router-dom

      - name: Run Tests
        run: |
          cd GIBBY_frontend
          CI=true npm test -- --no-watch --no-cache
        env:
          CI: true
          NODE_ENV: test

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v3
        with:
          repository: GIBBY-GDGoC-in-GIST/gibby-be
          path: gibby-be
          token: ${{ secrets.INTEGRATION_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'gibby-be/package-lock.json'

      - name: Install Dependencies
        run: |
          cd gibby-be
          npm ci

      - name: Run Tests
        run: |
          cd gibby-be
          npm test
        env:
          CI: true
          NODE_ENV: test

  integration-test:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v3
        with:
          repository: GIBBY-GDGoC-in-GIST/GIBBY_frontend
          path: GIBBY_frontend
          token: ${{ secrets.INTEGRATION_TOKEN }}

      - name: Checkout Backend
        uses: actions/checkout@v3
        with:
          repository: GIBBY-GDGoC-in-GIST/gibby-be
          path: gibby-be
          token: ${{ secrets.INTEGRATION_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd GIBBY_frontend && npm ci
          cd ../gibby-be && npm ci

      - name: Start Backend Server
        run: npm run start:dev
        working-directory: gibby-be
        env:
          NODE_ENV: test

      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: GIBBY_frontend
        env:
          CI: true
          API_URL: http://localhost:3000 
